## 1. Iris 데이터 품종 예측하기(내장데이터 이용)

In [27]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [12]:
iris=load_iris()

In [15]:
print(iris.feature_names)
print(iris.data)
print(iris.target_names)
print(iris.target)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3

In [21]:
import pandas as pd
df=pd.DataFrame(iris.data,columns=iris.feature_names) #feature
df['target']=iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [22]:
#데이터 분리(학습데이터, 테스트데이터)
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,
                                              test_size=0.2,random_state=11)

In [23]:
#fit
dt_clf=DecisionTreeClassifier(random_state=11)
dt_clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=11)

In [26]:
#pred
y_pred=dt_clf.predict(X_test)

In [28]:
#accuracy_score
accuracy_score(y_test,y_pred)

0.9333333333333333

## 2. model_selection
### 2.1 데이터 셋 분리
- 학습데이터
- 검증데이터: 학습데이터 분할하여 모델 일차 평가
- 테스트데이터: 모델 최종 평가

### 2.2 교차 검증
- k폴드
- stratified k폴드(레이블 분포 불균형할시)
- cross_val_score
- GridSearchCV

- k폴드

In [41]:
from sklearn.model_selection import KFold
import numpy as np
kfold=KFold(n_splits=5) #학습, 검증 데이터로 5번 쪼개기

cv=[]
dt_clf=DecisionTreeClassifier(random_state=11)

for train_index, test_index in kfold.split(iris.data):
    X_train,X_test=iris.data[train_index],iris.data[test_index]
    y_train,y_test=iris.target[train_index],iris.target[test_index]
    
    dt_clf.fit(X_train,y_train)
    y_pred=dt_clf.predict(X_test)
    
    cv.append(round(accuracy_score(y_test,y_pred),3))

print(cv)
print(round(np.mean(cv),3))
    

[1.0, 0.967, 0.867, 0.933, 0.833]
0.92


- stratified k폴드
> <strong> <k폴드와 차이점> <br>  </strong>
> kfold.split(iris.data) <br>
> skfold.split(iris.data,iris.target)

In [43]:
from sklearn.model_selection import StratifiedKFold
skfold=StratifiedKFold(n_splits=5)
cv=[]

for train_index, test_index in skfold.split(iris.data,iris.target):
    X_train,X_test=iris.data[train_index],iris.data[test_index]
    y_train,y_test=iris.target[train_index],iris.target[test_index]
    
    dt_clf.fit(X_train,y_train)
    y_pred=dt_clf.predict(X_test)
    
    cv.append(round(accuracy_score(y_test,y_pred),3))
    
print(cv)
print(round(np.mean(cv),3))

[0.967, 0.967, 0.9, 0.967, 1.0]
0.96


- cross_val_score

In [50]:
from sklearn.model_selection import cross_val_score

scores=cross_val_score(dt_clf,iris.data,iris.target,scoring='accuracy',cv=3)
print(np.round(scores,3))
print(np.round(np.mean(scores),3))

[0.98 0.92 0.98]
0.96


- GridSearchCV

In [75]:
from sklearn.model_selection import GridSearchCV
#train이랑 test분리
X_train, X_test, y_train, y_test=train_test_split(iris.data, iris.target, 
                                                 test_size=0.2, random_state=15)

#교차검증 3번, 가장 좋은 파라미터 찾기 (3*6=18번)
parameters={'max_depth':[1,2,3],'min_samples_split':[2,3]}
grid_dtree=GridSearchCV(dt_clf,param_grid=parameters, cv=3, refit=True, return_train_score=True)

grid_dtree.fit(X_train,y_train)
pred=grid_dtree.predict(X_test)
print(accuracy_score(y_test,pred)) #테스트 데이터 세트 정확도

0.9666666666666667


In [76]:
grid_dtree.best_params_

{'max_depth': 2, 'min_samples_split': 2}

In [77]:
grid_dtree.best_score_ #GridSearchCV 최고 정확도(parmaeter 계속 바뀌니까)

0.9083333333333333

## 3. 데이터 전처리
- 데이터 인코딩: 레이블 인코딩, 원-핫 인코딩
- 데이터 스케일링: 표준화, 정규화

In [81]:
#레이블 인코딩
from sklearn.preprocessing import LabelEncoder
items=['a','b','c','d','e','e','a','a','c']

encoder=LabelEncoder()
encoder.fit(items) #fit
labels=encoder.transform(items) #transform
print(labels)
print(encoder.classes_)

[0 1 2 3 4 4 0 0 2]
['a' 'b' 'c' 'd' 'e']


In [84]:
#원핫 인코딩
from sklearn.preprocessing import OneHotEncoder
items=np.array(items).reshape(-1,1) #2차원 ndarray로 변환

oh_encoder=OneHotEncoder()
oh_encoder.fit(items)
oh_labels=oh_encoder.transform(items)

oh_labels.toarray() #희소행렬이기 때문에 toarray() 이용해서 바꿔주자

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [87]:
#원핫 인코딩 다른 방법
df1=pd.DataFrame(items)
pd.get_dummies(df1)

0_a  0_b  0_c  0_d  0_e
0    1    0    0    0    0
1    0    1    0    0    0
2    0    0    1    0    0
3    0    0    0    1    0
4    0    0    0    0    1
5    0    0    0    0    1
6    1    0    0    0    0
7    1    0    0    0    0
8    0    0    1    0    0

In [93]:
#표준화
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(iris.data)
scaled=scaler.transform(iris.data)

scaled_df=pd.DataFrame(scaled,columns=iris.feature_names)
scaled_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [95]:
#정규화
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(iris.data)
scaled=scaler.transform(iris.data)

scaled_df=pd.DataFrame(scaled,columns=iris.feature_names)
scaled_df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            0.428704          0.440556           0.467458   
std             0.230018          0.181611           0.299203   
min             0.000000          0.000000           0.000000   
25%             0.222222          0.333333           0.101695   
50%             0.416667          0.416667           0.567797   
75%             0.583333          0.541667           0.694915   
max             1.000000          1.000000           1.000000   

       petal width (cm)  
count        150.000000  
mean           0.458056  
std            0.317599  
min            0.000000  
25%            0.083333  
50%            0.500000  
75%            0.708333  
max            1.000000